$kind: http-request
name: GET_tasks_no_header
url: "{{base_url}}/tasks"
method: GET
auth:
  type: bearer
  credentials:
    token: ""
scripts:
  - type: beforeRequest
    code: ""
    language: text/javascript
  - type: afterResponse
    code: "pm.test(\"Status code is 401\", function() {\r

      \    pm.response.to.have.status(401);\r

      \    console.log(pm.response.json());\r

      })"
    language: text/javascript
order: 1000
